"""add description in domain

Revision ID: 443a46113be3
Revises: eb54a9f65887
Create Date: 2019-03-01 13:44:56.945418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443a46113be3'
down_revision = 'eb54a9f65887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'description')
    # ### end Alembic commands ###
