"""add color in entity

Revision ID: dcb86617840f
Revises: 8d75162c88af
Create Date: 2019-03-08 17:19:17.667191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb86617840f'
down_revision = '8d75162c88af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('color_hex', sa.String(length=16)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'color_hex')
    # ### end Alembic commands ###
